version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
    environment:
      - "RABBITMQ_DEFAULT_PASS=ribbit"
      - "RABBITMQ_DEFAULT_USER=rabbit"
  brokerbe:
    container_name: brokerbe
    image: broker:latest
    build:
      context: .
      target: backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - rabbitmq_nodejs
  consumer:
    container_name: consumer
    image: consumer:latest
    build:
      context: .
      target: consumer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=300 -- node ./service/consumer.js'
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge
